# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [ master ]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: grantmcconnaughey/lintly-flake8-github-action@v1.0
        with:
          python-version: '3.7.7'
          deps_list: 'requirements.txt'
          # The GitHub API token to create reviews with
          token: ${{ secrets.GITHUB_TOKEN }}
          # Fail if "new" violations detected or "any", default "new"
          failIf: new
          event-type: flake8-event
          # Additional arguments to pass to flake8, default "." (current directory)
          args: "--ignore=E121"

  mypy:
    name: mypy
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
          deps_list: 'requirements.txt'
      - name: Run mypy
        run: |
          pip3 install .
          python3 -m mypy .

  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7.7'
      - name: Test
        uses: onichandame/python-test-action@master
        with:
          deps_list: 'requirements.txt'
